### PR TITLE
General enchanements

### PR DESCRIPTION
**Pull request by Leo40Git**
An addon to that advanced TSC parsing thingy I mande for txin.
When a TSC list with the old format is encountered, the `TscPane.getCommands()` method now skips reading the advanced variables and instead gives them standard values.
(yes, another pull request from me)

### CODE REVIEW

**Comment by Leo40Git** [comment]
DOUBLE CLICKING TO PLACE AN ENTITY RETURNS
(in other news, I'm not dead)

**Comment by taedixon** [comment]
was I like, somehow not clear at some point about how much I am opposed to bringing back the double click?

**Comment by Leo40Git** [comment]
would you rather people use an old version of booster's lab

**Comment by taedixon** [comment]
that's their choice

**Comment by Leo40Git** [comment]
okay what were the problems with double clicking for placing an entity because i might be able to fix them (tomorrow bc i'm going to sleep now)

**Comment by taedixon** [comment]
LMB is already used for:
- dragging the view
- trigger popup to select a single NPC from a stack
- drag-selecting NPCs
these are non-negotiable controls
furthermore, in Swing the double-click requires the mouse to not move a single pixel in between inputs which makes it fairly inconsistent even all by itself. Combined with several other actions tied to the same button it's way more ambiguous as to what is going to happen in any given situation and causes a lot of accidental inputs. There's just no way I can allow it from a design standpoint and the few people who are too stubborn to adjust to the new control are only hurting themselves.

**Comment by Leo40Git** [comment]
alright i'll remove it tomorrow

**Comment by Leo40Git** [comment]
rip double click

**Pull request closed without merging**
